### ISSUE TITLE
Provide a default logging.yaml file

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm_App#147]
Thus far we have allowed a simple set of defaults for pflogger and have required users to manually create a ```logging.yaml``` file to customize.  Further, they have to modify ```gcm_run.j``` to copy the config file into the scratch directory for the run.

Now it is time to include a default `logging.yaml` file in the GCM app and modify the setup script to automatically use that file by default.    I will follow up shortly with a sensible initial file, but I will expect it will change quickly as we do further deployment.

**Comment by mathomp4** [comment]
I have started #148 as a Draft PR so we can track this. It has my first attempts at what I think is needed. Probably wrong, but it's a good start.

**Comment by tclune** [comment]
```
schema_version: 1

###############################      
locks:
   mpi:
      class: MpiLock
      comm:  MPI_COMM_WORLD

###############################      
formatters:
   basic:
      class: Formatter
      format:  '%(name)a~: %(level_name)a~: %(message)a'
   mpi:
      class: MpiFormatter
      format:  '%(mpi_rank)i4.4~: %(name)~: %(level_name)a~: %(message)a'
      comm: MPI_COMM_WORLD
   column:
      class: Formatter
      format: '(%(i)i3.3,%(j)i3.3): %(level_name)'



###############################      
handlers:

   console:
      class: streamhandler
      formatter: basic
      unit: OUTPUT_UNIT
      level: WARNING
      
      
   warnings:
      class:  FileHandler
      filename: warnings_and_errors.log
      lock: mpi
      level: WARNING
      formatter: basic

   errors:
      class:  StreamHandler
      formatter: basic
      unit: ERROR_UNIT
      level: ERROR

   mpi_shared:
      class: FileHandler
      filename: allPEs.log
      formatter: mpi
      comm: MPI_COMM_WORLD
      lock: mpi
      rank_keyword: rank
      level: DEBUG

   mpi_debug:
      class: MpiFileHandler
      formatter: basic
      filename:  debug_%(rank)i3.3~.log
      comm: MPI_COMM_WORLD      
      rank_prefix: rank
      level: DEBUG

###############################      
root:
   parallel: true
   handlers: [warnings,errors]
   level: WARNING

###############################      
loggers:

   errors:
       handlers: [errors]
       parallel: true
       lock: mpi
       level: ERROR

   CAP:
       parallel: true
       handlers: [console]
       lock: mpi
       level: WARNING
       root_level: INFO
       
   MAPL:
       parallel: true
       handlers: [mpi_shared]
       lock: mpi
       propagate: false
       level: INFO
       root_level: DEBUG

#   MAPL.base
#   MAPL.generic
#   MAPL.pfio



#   CAP
#   CAP.GCM
#   CAP.GCM.OGCM
#   CAP.GCM.DATAATM
#   CAP.GCM.AGCM
#   CAP.GCM.AIAU
#   CAP.GCM.ADFI
#   CAP.GCM.OGCM
#   CAP.GCM.AGCM.SCMDYNAMICS
#   CAP.GCM.AGCM.SUPERDYNAMICS
#   CAP.GCM.AGCM.PHYSICS
#   CAP.GCM.AGCM.ORBIT
#   CAP.GCM.AGCM.PHYSICS.GWD
#   CAP.GCM.AGCM.PHYSICS.MOIST
#   CAP.GCM.AGCM.PHYSICS.TURBULENCE
#   CAP.GCM.AGCM.PHYSICS.CHEMISTRY
#   CAP.GCM.AGCM.PHYSICS.SURFACE
#   CAP.GCM.AGCM.PHYSICS.RADIATION
#   CAP.GCM.OGCM.OBIO
#   CAP.GCM.OGCM.ORAD
#   CAP.GCM.OGCM.SEAICE
#   CAP.GCM.OGCM.SEAICEdata
#   CAP.GCM.OGCM.OCEAN
```

**Comment by mathomp4** [comment]
Okay. I've added that as `logging.yaml` on PR #148

**Comment by mathomp4** [comment]
@tclune it looks like this `logging.yaml` moved output from the stdout to a log file:
```
0000: MAPL.SHMEM: INFO: NumCores per Node varies from 16 to 40
0000: MAPL.SHMEM: INFO: NumNodes in use   = 3
0000: MAPL.SHMEM: INFO: Total PEs         = 96
0000: MAPL.SHMEM: INFO: NumNodes in use  = 3
```
This info is quite useful to have in the "main" log file as well. Is there a way to send it to both a logfile in `scratch/` and to the "main" stdout?

**Comment by tclune** [comment]
Yes.  The issue is that there are too many ways.   All messages get routed up to the "ROOT" logger.  So if you want INFO level messages to go to STDOUT, you need to set the block for the root logger to:
```yaml
root:
   parallel: true
   handlers: [warnings,errors]
   level: WARNING
   root_level: INFO
```
The terminology is confusing because the ROOT logger is the ancestor of the loggers, but "root_level" refers to the rank 0 process.

My expectation is that once people are comfortable with being able to get this information by modifying the yaml file, they won't feel like it is needed in every run.   But there is no reason to rush culture change.

**Comment by mathomp4** [comment]
@tclune Thanks. I'll test it soon. (Guess who was dumb and was doing his work in a nightly-build model? Sigh. Oh well, at least I pushed to Github!)

**Comment by mathomp4** [comment]
Hmm. I just changed the `logging.yaml` file to use:
```yaml
root:
   parallel: true
   handlers: [warnings,errors]
   level: WARNING
   root_level: INFO
```
and the SHMEM messages are still only in the `AllPEs.log` file:
```
0000: MAPL.SHMEM: INFO: NumCores per Node varies from 16 to 40
0000: MAPL.SHMEM: INFO: NumNodes in use   = 3
0000: MAPL.SHMEM: INFO: Total PEs         = 96
0000: MAPL.SHMEM: INFO: NumNodes in use  = 3
```
